function XBGenfun(profile, Ho, T, duration)

  %  load  ../Final_TWL_Profiles_03222022.mat;
    current_folder = pwd;
    cd('C:\Users\rf20354\Documents\Research\RC_Profiles')
    load('Final_TWL_Profiles_03222022.mat');
    cd(current_folder)
    prof = profile;

    xbi = xb_generate_model( ...
             'bathy',   { 'x', Profile(prof).Xshore, 'z', Profile(prof).Prof},...
             'waves',   { 'Hm0', Ho, 'Tp', T,'duration',duration}, ...
             'settings', {'morphology', 0, 'sedtrans', 0, 'wavemodel','surfbeat','snells', 0, 'tstop', duration,...
             'zs0',Profile(prof).zdatum, 'nglobalvar', {'H' 'zb' 'zs'},...
             'npoints',{'0 0'}, 'npointvar', {'zb','zs','H'}, 'nrugauge', {'0 0'}});
    xb_write_input('params.txt', xbi);
    load('x.grd')
    point = [num2str(x(1)),' 0'];
    xbi = xb_generate_model( ...
             'bathy',   { 'x', Profile(prof).Xshore, 'z', Profile(prof).Prof},...
             'waves',   { 'Hm0', Ho, 'Tp', T,'duration',duration}, ...
             'settings', {'morphology', 0, 'sedtrans', 0, 'wavemodel','surfbeat','snells', 0, 'tstop', duration,...
             'zs0',Profile(prof).zdatum, 'nglobalvar', {'H' 'zb' 'zs'},...
             'npoints',{point}, 'npointvar', {'zb','zs','H'}, 'nrugauge', {point}});
    xb_write_input('params.txt', xbi);
    system('C:\Users\rf20354\Documents\xbeach_5849_win32_netcdf\xbeach.exe')
    pause(4)
    Runup_1Dfun('xboutput.nc',Ho,T,profile)
end